import type { FingerName } from './types.ts'

/** MediaPipe's 21-point hand landmark topology. */
export const HAND_LANDMARK = {
  WRIST: 0,
  THUMB_CMC: 1,
  THUMB_MCP: 2,
  THUMB_IP: 3,
  THUMB_TIP: 4,
  INDEX_MCP: 5,
  INDEX_PIP: 6,
  INDEX_DIP: 7,
  INDEX_TIP: 8,
  MIDDLE_MCP: 9,
  MIDDLE_PIP: 10,
  MIDDLE_DIP: 11,
  MIDDLE_TIP: 12,
  RING_MCP: 13,
  RING_PIP: 14,
  RING_DIP: 15,
  RING_TIP: 16,
  PINKY_MCP: 17,
  PINKY_PIP: 18,
  PINKY_DIP: 19,
  PINKY_TIP: 20,
} as const

export const LANDMARK_COUNT = 21

export const FINGER_NAMES: readonly FingerName[] = ['thumb', 'index', 'middle', 'ring', 'pinky']

/** Joint indices per finger, ordered base to tip. */
export const FINGER_JOINTS: Record<FingerName, readonly number[]> = {
  thumb: [HAND_LANDMARK.THUMB_CMC, HAND_LANDMARK.THUMB_MCP, HAND_LANDMARK.THUMB_IP, HAND_LANDMARK.THUMB_TIP],
  index: [HAND_LANDMARK.INDEX_MCP, HAND_LANDMARK.INDEX_PIP, HAND_LANDMARK.INDEX_DIP, HAND_LANDMARK.INDEX_TIP],
  middle: [HAND_LANDMARK.MIDDLE_MCP, HAND_LANDMARK.MIDDLE_PIP, HAND_LANDMARK.MIDDLE_DIP, HAND_LANDMARK.MIDDLE_TIP],
  ring: [HAND_LANDMARK.RING_MCP, HAND_LANDMARK.RING_PIP, HAND_LANDMARK.RING_DIP, HAND_LANDMARK.RING_TIP],
  pinky: [HAND_LANDMARK.PINKY_MCP, HAND_LANDMARK.PINKY_PIP, HAND_LANDMARK.PINKY_DIP, HAND_LANDMARK.PINKY_TIP],
}

/** Landmarks used to approximate the palm center. */
export const PALM_LANDMARKS: readonly number[] = [
  HAND_LANDMARK.WRIST,
  HAND_LANDMARK.INDEX_MCP,
  HAND_LANDMARK.MIDDLE_MCP,
  HAND_LANDMARK.RING_MCP,
  HAND_LANDMARK.PINKY_MCP,
]

/** Skeleton edges for debug-overlay drawing. */
export const HAND_CONNECTIONS: ReadonlyArray<readonly [number, number]> = [
  [HAND_LANDMARK.WRIST, HAND_LANDMARK.THUMB_CMC],
  [HAND_LANDMARK.THUMB_CMC, HAND_LANDMARK.THUMB_MCP],
  [HAND_LANDMARK.THUMB_MCP, HAND_LANDMARK.THUMB_IP],
  [HAND_LANDMARK.THUMB_IP, HAND_LANDMARK.THUMB_TIP],
  [HAND_LANDMARK.WRIST, HAND_LANDMARK.INDEX_MCP],
  [HAND_LANDMARK.INDEX_MCP, HAND_LANDMARK.INDEX_PIP],
  [HAND_LANDMARK.INDEX_PIP, HAND_LANDMARK.INDEX_DIP],
  [HAND_LANDMARK.INDEX_DIP, HAND_LANDMARK.INDEX_TIP],
  [HAND_LANDMARK.INDEX_MCP, HAND_LANDMARK.MIDDLE_MCP],
  [HAND_LANDMARK.MIDDLE_MCP, HAND_LANDMARK.MIDDLE_PIP],
  [HAND_LANDMARK.MIDDLE_PIP, HAND_LANDMARK.MIDDLE_DIP],
  [HAND_LANDMARK.MIDDLE_DIP, HAND_LANDMARK.MIDDLE_TIP],
  [HAND_LANDMARK.MIDDLE_MCP, HAND_LANDMARK.RING_MCP],
  [HAND_LANDMARK.RING_MCP, HAND_LANDMARK.RING_PIP],
  [HAND_LANDMARK.RING_PIP, HAND_LANDMARK.RING_DIP],
  [HAND_LANDMARK.RING_DIP, HAND_LANDMARK.RING_TIP],
  [HAND_LANDMARK.RING_MCP, HAND_LANDMARK.PINKY_MCP],
  [HAND_LANDMARK.PINKY_MCP, HAND_LANDMARK.PINKY_PIP],
  [HAND_LANDMARK.PINKY_PIP, HAND_LANDMARK.PINKY_DIP],
  [HAND_LANDMARK.PINKY_DIP, HAND_LANDMARK.PINKY_TIP],
  [HAND_LANDMARK.WRIST, HAND_LANDMARK.PINKY_MCP],
]
